### ISSUE TITLE
"Remove trait" missing from collections

### ISSUE THREAD

**Issue by zsloan** [zsloan/genenetwork2#11]
The option to remove traits is missing from the collection page. This option used to exist, so it must have been either mistakenly or purposely removed/commented out for some reason.

**Comment by lomereiter** [comment]
Found the commit which removed buttons `Add record to other collection`, `Remove record`, and `Download table` from the collection page: https://github.com/zsloan/genenetwork2/commit/c05b56d96d0a86a0c88daea6ec5c68c5856741cd

**Comment by zsloan** [comment]
This issue was moved to genenetwork/genenetwork2#13
