### ISSUE TITLE
Large files need to be stored in shared directory

### ISSUE THREAD

**Issue by pjotrp** [zsloan/genenetwork2#13]
The idea is to have a shared storage for a server. E.g.

STORAGE=/export/local/gn2/storage

This can be set in the configuration for every running server. Within the storage dir we'll use MD5 values (of the contained files) to uniquely set the dirname, e.g.

/export/local/gn2/storage/d849b0238cd26434237b28498628837d/files...

That hash value will be used to locate the data.

**Comment by zsloan** [comment]
This issue was moved to genenetwork/genenetwork2#15
