### ISSUE TITLE
Traits are assumed to be log-scaled

### ISSUE THREAD

**Issue by lomereiter** [zsloan/genenetwork2#19]
E.g. page for the trait with id 10001 (where the unit is mg/dl) shows inadequate range statistics

![trait10001](https://cloud.githubusercontent.com/assets/662555/7492577/ee125ab4-f401-11e4-88ff-b9d62929e62f.png)

**Comment by zsloan** [comment]
Yeah, our Range statistic not being calculated properly is an issue we're
aware of.

**Comment by zsloan** [comment]
This issue was moved to genenetwork/genenetwork2#2
