### ISSUE TITLE
Combined search doesn't work for most search types

### ISSUE THREAD

**Issue by lomereiter** [zsloan/genenetwork2#5]
Only a single class, MrnaAssaySearch, has `run_combined` method, all the other classes in `do_search.py` are required to have this method since [this](https://github.com/zsloan/genenetwork2/commit/e0bd0ab02d26fd8520ddfb0f69baa746ddee91fe) commit but don't have it.

**Comment by zsloan** [comment]
This issue was moved to genenetwork/genenetwork2#8
